#!/bin/bash

# afiseaza cele mai mari 10 fisiere dintr-un director dat

find $1 -type f -exec du -hs {} + | sort -hr | awk 'FNR <=10'


#du -bh  $1/* | sort -r | awk 'FNR <=10'

#all=$(ls -Fl $1 | awk '{print $5 "-" $9}' | sort )
#list=( $all )
#file=()
#for each in ${list[@]}
#do
#	echo ${each%/*}
#	file+="${each%/*} "
#done

#aux=($file)
#sorted=($(sort <<<"${aux[*]}"))
#echo ${sorted[@]}

